### PR TITLE
16 settings button

### PR DESCRIPTION
**Pull request by Benek6h**
I added a button labeled settings that when tapped on will navigate to the settings page. 
The output is shown in the video below.
:3

[SettingsButtonVid.webm](https://github.com/S1robe/Pocket-Therapist/assets/143664609/565932f5-34f8-4648-99c6-a39657f974b7)

### CODE REVIEW

**Review by Cooljawty — APPROVED** [review]
Works fine on my end, and is covered in testing
Id probably remove the button shadow since i don't think we have any in the prototype, but it's not entirely necessary at this point.

**Comment by S1robe** [comment]
Please fix the above conflicts, additionally remove the button from the dashboard. Looks great!

**Review by S1robe — APPROVED** [review]
Changes approved, thank you for resolving commits and implementing the settings button.

**Review by S1robe — APPROVED** [review]
Thank you for fixing the conflicts with main, settings button looks complete

**Pull request merged**
