### PR TITLE
18 start button password integration

### PR DESCRIPTION
**Pull request by Benek6h**
# Description

Integrated logic for password field to set a password and on incorrect password.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Test A Setting up an Account Without a password and choosing no password on set up
  -initial screen for new user
StartScreenInitial
  -user hits start and is prompted if they want to set up a password
StartScreenFirstTimeUser
   -After hitting no the user is taken to the dashboard, upon reopening the app we are greeted by a similar looking welcome page but after start is hit then we advance to the dashboard instead of prompting the user to set up a password again.
StartScreenLockedWithoutPassword

- [ ] Test B Setting up a new account with a password
   -inital screen for new user
StartScreenInitial
   -user hits start and is prompted if they want to set up a password
StartScreenFirstTimeUser
   -user hits yes and is then prompted for a password to user (if left empty then we treat it like no password chosen)
StartScreenPasswordSetup
   -After hitting save password the password is updated and every time the user opens the app they will first be prompted with the login page before they can get to the dashboard.
StartScreenLocked
   -After inputting the correct password the form will need to be submitted to gain access to the dashboard. if the Incorrect password is inputted then the form is cleared and the user can try again.

- [ ] Test C Flutter test
  - We implement 2 new test and modify the previous 3 that were used to test the start button. These test are fully functional and test to ensure what is displayed on the screen is expected and test to ensure that the user can log in using the passwordField if a password is set up.

**Test Configuration**:
* Firmware version: Android 14
* Hardware: Google Pixel 7
* Toolchain: Android API 34
* SDK: sdk_gphone6_65

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Benek6h** [comment]
If the user doesn't submit their password, we shouldn't tell them that they gained access. This should be onSubmitted or when enter is pressed.

**Comment by JikoJeans** [comment]
Final updates have been made for this feature, we are ready for last glance reviews and feedback.

**Review by S1robe — APPROVED** [review]
Everything looks great, Thank you both for tackling this.

**Review by ian5924 — APPROVED** [review]
Everything looks good.

**Pull request merged**
