### PR TITLE
Update PULL_REQUEST_GUIDE.md

### PR DESCRIPTION
**Pull request by S1robe**
This adapts the old PR approval guide to our new code base. Things like "Is there continuous integration" were removed, because we have always had these.

Please review and provide feedback.
Thank you.

## Type of change

Please delete options that are not relevant.

- [x] This change updates documentation

### CODE REVIEW

**Comment by ian5924** [comment]
@S1robe Do you think the guide should include a demonstration through a video or image?

**Comment by S1robe** [comment]
@ian5924 Guide for what? Using the checklist is clear isnt it? If you mean the code base there is one for the the new test methods.

**Comment by ian5924** [comment]
> @ian5924 Guide for what? Using the checklist is clear isnt it? If you mean the code base there is one for the the new test methods.

I was talking about the checklist itself, but it does cover everything we need.

**Review by ian5924 — APPROVED** [review]
These are thorough, great job.
I think it covers everything we need to look for when reviewing.

**Review by JikoJeans — APPROVED** [review]
Everything looks good thank you for the update.

**Pull request merged**
