### PR TITLE
Cleaning up project and updating gitignore

### PR DESCRIPTION
**Pull request by S1robe**
Cleaning up the project repo before it gets out of hand. 
If you need any of the previous files, 

`flutter create .`

will regenerate the other platforms. 
This PR removes the following directories and adds them to the .gitignore
- /windows
- /coverage
- /web
- /linux
- /macos

The only file in /coverage is 'lcov.info' which is auto generated by `flutter test`

### CODE REVIEW

**Comment by JikoJeans** [comment]
Everything looks good to go.

**Review by Cooljawty — CHANGES_REQUESTED** [review]
It builds fine, but it seems to get an error when compileing the widget test:
```
est/widget_test.dart:16:35: Error: Couldn't find constructor 'MyApp'.
    await tester.pumpWidget(const MyApp());

```

**Comment by S1robe** [comment]
I do not have this issue, the checks also run the tests in an isolated environment.
Are you certain something is wrong?

You are also running something incorrectly, there is no file named "widget_test.dart" in this branch. 

Please try run them again, and approve if no issues are found.

image

**Review by Cooljawty — APPROVED** [review]
Ok think i had an old test from another branched saved.
After wiping and cloning fresh the test is working.

**Review by Benek6h — APPROVED** [review]
No more conflicts!
Looks great!

**Pull request merged**
